services:
  postgres:
    container_name: postgres-sql-ssa
    image: postgres
    environment:
      POSTGRES_USER: amila
      POSTGRES_PASSWORD: amila
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: spring_security_application
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-security
    restart: unless-stopped


  mail-dev:
    container_name: mail-dev-ssa
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-security

  keycloak:
    container_name: keycloak-ssa
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-security
    command:
      - "start-dev"


networks:
  spring-security:
    driver: bridge
volumes:
  postgres:
    driver: local